server:
  port: 5000

spring:
  application:
    name: client-service

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:client
    username : admin
    password: admin

  h2:
    console:
      enabled: true

logging:
  level:
    com:
      client: INFO

#resilience4j.circuitbreaker:
#  instances:
#    productCB:
#      registerHealthIndicator: true
#      slidingWindowSize: 10
#      permittedNumberOfCallsInHalfOpenState: 3
#      slidingWindowType: TIME_BASED
#      minimumNumberOfCalls: 20
#      waitDurationInOpenState: 50s
#      failureRateThreshold: 50
#      eventConsumerBufferSize: 10