-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table clients
create table clients (
    id_client integer generated by default as identity,
    address varchar(255),
    age integer,
    identification integer,
    name varchar(255),
    phone varchar(255),
    password varchar(255),
    state boolean, id_gender_fk integer,
   primary key (id_client)
);

-- changeset script:2
-- comment: Creation table genders
create table genders (
    id_gender integer generated by default as identity,
    name varchar(255),
    primary key (id_gender)
);


-- changeset script:11
-- comment: Creation genders
INSERT INTO genders(name) VALUES
    ( 'Male' ),
    ( 'Female' );

---- changeset script:12
---- comment: Creation products
insert into clients (address, age, id_gender_fk, identification, name, password, phone, state) values
    ('calle 89 No 22 - 36', 20, 1, 963258741, 'Carlos Stiven', 'pass', '3112658974', true)

