-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table account_types
create table account_types (
    id_account_type integer generated by default as identity,
    name_account_type varchar(255),
    primary key (id_account_type)
);

-- changeset script:2
-- comment: Creation table genders
create table movement_types (
    id_movement_type integer generated by default as identity,
    name varchar(255),
    primary key (id_movement_type)
);

-- changeset script:3
-- comment: Creation table accounts
create table accounts (
    account_number integer not null,
    id_client integer,
    init_balance numeric(38,2),
    state boolean,
    id_account_type_fk integer,
    primary key (account_number)
);

-- changeset script:4
-- comment: Creation table movements
create table movements (
    id_movement integer generated by default as identity,
    ammount numeric(38,2),
    date timestamp(6),
    total_balance numeric(38,2),
    id_account_fk integer,
    id_movement_type_fk integer,
    primary key (id_movement)
);

-- changeset script:11
-- comment: Creation account_types
INSERT INTO account_types(name_account_type) VALUES
    ( 'Saving' ),
    ( 'Current' );

-- changeset script:12
-- comment: Creation movement_types
insert into movement_types (name) values
    ( 'Withdrawal' ),
    ( 'Deposit' );

-- changeset script:13
-- comment: Creation accounts
insert into accounts (account_number, id_account_type_fk, id_client ,init_balance ,state) values
    (12345, 1, 1, 100, true);

-- changeset script:14
-- comment: Creation movements
insert into movements (id_account_fk, ammount, date, id_movement_type_fk, total_balance) values
    (12345, 100, '2020-12-31 23:59:59', 2, 200)